name: Frontend Linting

on:
  push:
    paths:
      - frontend/**
    branches:
      - main
  pull_request:
    paths:
      - frontend/**

jobs:
  eslint:
    name: ESLint (Frontend)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint